Update media-sound/flac123 to 0.0.12 from 0.0.11
Exherbo/media-unofficial pull request #5
Opened 2021-08-12 03:27 UTC by Archetypic

2021-08-12 07:59 UTC, tgurr commented
**404: Not Found.** It doesn't even fetch for me, the tarball for 0.0.12 carries an additional **-release** in its name so the exheres has to reflect that as well.

2021-08-12 12:55 UTC, Archetypic commented
Which file will tell me the `supported_autoconf` as well as `supported_automake` versions?

2021-08-12 13:04 UTC, tgurr commented
> Which file will tell me the `supported_autoconf` as well as `supported_automake` versions?

Most recent versions should go first `1.14 1.15 1.16` -> `1.16 1.15 1.14`.

Only the most recent version for each should be added if it works with that. Usually when you see more than one version the package may be older so it has been added when 1.14 was the most recent one and then 1.15 and 1.16 got added after things were confirmed working with these newer versions.

2021-08-12 13:34 UTC, Archetypic commented
Thank you for your assistance and patience.

2021-08-12 14:59 UTC, tgurr requested changes
No problem at all, and sorry for e.g. not making use of the GitHub review functions earlier already. Could you please squash your commits to just the version bump? I don't think the details are of much use and rather self-explanatory.

2021-08-12 14:59 UTC, tgurr commented on packages/media-sound/flac123/flac123-0.0.12.exheres-0
> +require autotools [ supported_autoconf=[ 2.5 ] supported_automake=[ 1.16 1.15 1.14 ] ]
for autoconf there's 2.7 and just use only latest if adding it just now, so I'd suggest:
`require autotools [ supported_autoconf=[ 2.7 ] supported_automake=[ 1.16 ] ]`

2021-08-12 22:13 UTC, Archetypic commented
I have enabled "Allow squash merging" in the fork.

https://postimg.cc/XrzNpqyT

I assume this is insufficient due to your direct request. I will squash, just want confirmation on this.

2021-08-13 07:30 UTC, merged

2021-08-13 07:45 UTC, tgurr commented
> I have enabled "Allow squash merging" in the fork.
> 
> https://postimg.cc/XrzNpqyT
> 
> I assume this is insufficient due to your direct request.

Thanks, that's fine, GitHub provides an option to `Squash and merge` on merging the pull request, see:

![Screenshot_20210813_092615](https://user-images.githubusercontent.com/414984/129321071-bbf326d5-6a1d-493a-8843-15bed8815717.png)

Thanks for your contribution and patience!